site_name: Python 数据结构与算法视频教程
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$

nav:
    - 课程简介: 'index.md'
    - 00_课程简介之笨方法学算法: '00/why_and_how_to_learn.md'
    - 01_抽象数据类型和面向对象编程: '01/ADT_OOP.md'
    - 02_数组和列表: '02/array_and_list.md'
    - 03_链表: '03/linked_list.md'
    - 04_队列: '04/queue.md'
    - 05_栈: '05/stack.md'
    - 06_算法分析: '06/big_o.md'
    - 07_哈希表: '07/hashtable.md'
    - 08_字典: '08/dict.md'
    - 09_集合: '09/set.md'
    - 10_递归: '10/recursion.md'
    - 11_线性查找与二分查找: '11/search.md'
    - 12_基本排序算法: '12/basic_sort.md'
    - 13_高级排序算法:
      - 高级排序算法: '13/advanced_sorting.md'
      - 分治法与归并排序: '13/merge_sort.md'
      - 快速排序: '13/quick_sort.md'
    - 14_树与二叉树: '14/tree.md'
    - 15_堆和堆排序: '15/heap_and_heapsort.md'
    - 16_优先级队列: '16/priority_queue.md'
    - 17_二叉查找树: '17/binary_search_tree.md'
    - 18_图与图的遍历: '18/graph.md'
    - 19_python内置常用算法和数据结构: '19/builtins.md'
    - 20_面试指南: '20/interview.md'
